<nav>
	<ul id="nav_buttons">
		<li><a id="home_link" class="nav_button button home" href="/"><span class="translate" data-lang-ja="<?php echo $button_interfaces['home_page']['ja']; ?>" data-lang-zh="<?php echo $button_interfaces['home_page']['zh']; ?>" data-lang-es="<?php echo $button_interfaces['home_page']['es']; ?>" data-lang-ru="<?php echo $button_interfaces['home_page']['ru']; ?>" data-lang-en="<?php echo $button_interfaces['home_page']['en']; ?>" data-lang-vi="<?php echo $button_interfaces['home_page']['vi']; ?>"><?php echo $button_interfaces['home_page'][$lang_code]; ?></span></a></li>
		<li><a id="intro_link" class="nav_button button intro" href="/introduction/"><span class="translate" data-lang-ja="<?php echo $button_interfaces['intro']['ja']; ?>" data-lang-zh="<?php echo $button_interfaces['intro']['zh']; ?>" data-lang-es="<?php echo $button_interfaces['intro']['es']; ?>" data-lang-ru="<?php echo $button_interfaces['intro']['ru']; ?>" data-lang-en="<?php echo $button_interfaces['intro']['en']; ?>" data-lang-vi="<?php echo $button_interfaces['intro']['vi']; ?>"><?php echo $button_interfaces['intro'][$lang_code]; ?></span></a></li>
		<li><a id="lunar_link" class="nav_button button lunar" href="/xemngay/"><span class="translate" data-lang-ja="<?php echo $button_interfaces['lunar']['ja']; ?>" data-lang-zh="<?php echo $button_interfaces['lunar']['zh']; ?>" data-lang-es="<?php echo $button_interfaces['lunar']['es']; ?>" data-lang-ru="<?php echo $button_interfaces['lunar']['ru']; ?>" data-lang-en="<?php echo $button_interfaces['lunar']['en']; ?>" data-lang-vi="<?php echo $button_interfaces['lunar']['vi']; ?>"><?php echo $button_interfaces['lunar'][$lang_code]; ?></span></a></li>
		<li><a id="bmi_link" class="nav_button button bmi" href="/bmi/"><span class="translate" data-lang-ja="<?php echo $button_interfaces['bmi']['ja']; ?>" data-lang-zh="<?php echo $button_interfaces['bmi']['zh']; ?>" data-lang-es="<?php echo $button_interfaces['bmi']['es']; ?>" data-lang-ru="<?php echo $button_interfaces['bmi']['ru']; ?>" data-lang-en="<?php echo $button_interfaces['bmi']['en']; ?>" data-lang-vi="<?php echo $button_interfaces['bmi']['vi']; ?>"><?php echo $button_interfaces['bmi'][$lang_code]; ?></span></a></li>
		<li><a id="game_link" class="nav_button button game" href="/game/"><span class="translate" data-lang-ja="<?php echo $button_interfaces['game']['ja']; ?>" data-lang-zh="<?php echo $button_interfaces['game']['zh']; ?>" data-lang-es="<?php echo $button_interfaces['game']['es']; ?>" data-lang-ru="<?php echo $button_interfaces['game']['ru']; ?>" data-lang-en="<?php echo $button_interfaces['game']['en']; ?>" data-lang-vi="<?php echo $button_interfaces['game']['vi']; ?>"><?php echo $button_interfaces['game'][$lang_code]; ?></span></a></li>
		<li><a id="blog_link" class="nav_button button" href="/blog/"><span class="translate" data-lang-ja="<?php echo $button_interfaces['blog']['ja']; ?>" data-lang-zh="<?php echo $button_interfaces['blog']['zh']; ?>" data-lang-es="<?php echo $button_interfaces['blog']['es']; ?>" data-lang-ru="<?php echo $button_interfaces['blog']['ru']; ?>" data-lang-en="<?php echo $button_interfaces['blog']['en']; ?>" data-lang-vi="<?php echo $button_interfaces['blog']['vi']; ?>"><?php echo $button_interfaces['blog'][$lang_code]; ?></span></a></li>
		<li><a id="forum_link" class="nav_button button" href="http://diendan.nhipsinhhoc.vn"><span class="translate" data-lang-ja="<?php echo $button_interfaces['forum']['ja']; ?>" data-lang-zh="<?php echo $button_interfaces['forum']['zh']; ?>" data-lang-es="<?php echo $button_interfaces['forum']['es']; ?>" data-lang-ru="<?php echo $button_interfaces['forum']['ru']; ?>" data-lang-en="<?php echo $button_interfaces['forum']['en']; ?>" data-lang-vi="<?php echo $button_interfaces['forum']['vi']; ?>"><?php echo $button_interfaces['forum'][$lang_code]; ?></span></a></li>
	</ul>
</nav>